[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''

(
  /(
    | .flake8
    | CONTRIBUTING.md
    | htmls.txt
    | ignoreURL.txt
    | LICENSE
    | pyproject.toml
    | README.md
  )/
  
)
'''